server:
  port: 8002

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://34.68.3.131:8761//eureka
    fetch-registry: true
    register-with-eureka: true

spring:
  mvc:
    hidden-method:
      filter:
        enabled: true
  application:
    name: SOCIALROOM
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true
#      path: /h2-console
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb;MODE=MySQL
#    username: sa
#    password : 1234
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.170.121.78:3306/iljo_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: iljo

  cloud:
     gcp:
       credentials:
         location: classpath:student-project-2022-368005-e4a467c21c2c.json

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  logging.level:
    org.hibernate.SQL: debug
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#  devtools:
#    add-properties:
#    password : 1234

spring.devtools.livereload.enabled: false


