server:
  port: 8003

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://34.68.3.131:8761/eureka
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: userEvaluation
#  h2:
#    console:
##      enabled : true
#      settings:
#        web-allow-others : true
#      path: /h2-console
#  datasource:
#    driver-class-name : org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password: 1234

  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.170.121.78:3306/iljo_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: iljo
  #    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    logging.level:
      org.hibernate.SQL: debug
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


